AWSTemplateFormatVersion: '2010-09-09'
Description: 'GenAI Bot - AI Services Stack (OpenSearch, Lex)'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, prod]
    Description: Environment name
  ProjectId:
    Type: String
    Description: Project ID
  PortfolioId:
    Type: String
    Description: Portfolio ID
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of Subnet IDs
  KnowledgeBaseSourceBucketName:
    Type: String
    Description: Name of the S3 Bucket for Knowledge Base Source

Resources:
  # OpenSearch Domain - Keeping for legacy/potential hybrid use, but removing if strict Kendra only. 
  # User asked to check changes, not delete resources unless necessary. 
  # Current Bedrock config uses Kendra, so OpenSearch is unused by Bedrock but might be used by checking `OpenSearchEndpoint` in ComputeStack.
  # Leaving OpenSearchDomain for now to avoid breaking other dependencies in ComputeStack.

  OpenSearchDomain:
    Type: AWS::OpenSearchService::Domain
    Properties:
      DomainName: !Sub chatbot-${ProjectId}-${PortfolioId}-${Environment}-os
      EngineVersion: 'OpenSearch_2.11'
      ClusterConfig:
        InstanceType: 't3.small.search'
        InstanceCount: 1
        DedicatedMasterEnabled: false
        ZoneAwarenessEnabled: false
      EBSOptions:
        EBSEnabled: true
        VolumeSize: 10
        VolumeType: gp3
      EncryptionAtRestOptions:
        Enabled: true
      NodeToNodeEncryptionOptions:
        Enabled: true
      DomainEndpointOptions:
        EnforceHTTPS: true
        TLSSecurityPolicy: Policy-Min-TLS-1-2-2019-07
      AccessPolicies:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'es:*'
            Resource: !Sub 'arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/chatbot-${ProjectId}-${PortfolioId}-${Environment}-os/*'

  # Lex Bot Role
  LexBotRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lex.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LexRuntimePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - polly:SynthesizeSpeech
                Resource: '*'

  # Kendra Service Role
  KendraServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: kendra.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: KendraS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::${KnowledgeBaseSourceBucketName}
                  - !Sub arn:aws:s3:::${KnowledgeBaseSourceBucketName}/*
        - PolicyName: KendraCloudWatchAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudwatch:PutMetricData
                  - logs:DescribeLogGroups
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

  # Bedrock Service Role
  BedrockServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: bedrock.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: BedrockKendraAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - kendra:Retrieve
                  - kendra:Query
                Resource: !Sub arn:aws:kendra:${AWS::Region}:${AWS::AccountId}:index/${KendraIndex}
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                Resource: arn:aws:bedrock:us-east-1::foundation-model/amazon.titan-embed-text-v1

  ####################
  # Kendra
  ####################
  KendraIndex:
    Type: AWS::Kendra::Index
    Properties:
      Name: !Sub "${AWS::StackName}-kendra-index"
      RoleArn: !GetAtt KendraServiceRole.Arn
      Edition: GEN_AI_ENTERPRISE_EDITION
      Tags:
        - Key: Project
          Value: genai-chat-bot
        - Key: Stack
          Value: !Ref AWS::StackName
        - Key: Name
          Value: !Sub "${AWS::StackName}-kendra-index"

  KendraDataSource:
    Type: AWS::Kendra::DataSource
    DependsOn: KendraIndex
    Properties:
      Name: !Sub "${AWS::StackName}-kendra-s3-ds"
      IndexId: !Ref KendraIndex
      Type: S3
      DataSourceConfiguration:
        S3Configuration:
          BucketName: !Ref KnowledgeBaseSourceBucketName
      RoleArn: !GetAtt KendraServiceRole.Arn
      Tags:
        - Key: Project
          Value: genai-chat-bot
        - Key: Stack
          Value: !Ref AWS::StackName
        - Key: Name
          Value: !Sub "${AWS::StackName}-kendra-datasource"

  # Removed KendraWaiterLambdaRole placeholder as it was incomplete - better to rely on CloudFormation standard waiting or normal resource creation.

  BedrockKnowledgeBase:
    Type: AWS::Bedrock::KnowledgeBase
    Properties:
      Name: !Sub chatbot-${ProjectId}-${PortfolioId}-${Environment}-kb
      RoleArn: !GetAtt BedrockServiceRole.Arn
      Description: "Knowledge base backed by Kendra"
      KnowledgeBaseConfiguration:
        Type: KENDRA
        KendraKnowledgeBaseConfiguration:
          KendraIndexArn: !Sub "arn:aws:kendra:${AWS::Region}:${AWS::AccountId}:index/${KendraIndex}"
      Tags:
        Project: genai-chat-bot
        Stack: !Ref AWS::StackName
        Name: !Sub "${AWS::StackName}-bedrock-kb"

  # Lex Bot (Basic Placeholder)
  GenAIBot:
    Type: AWS::Lex::Bot
    Properties:
      Name: !Sub GenAIBot_${Environment}
      RoleArn: !GetAtt LexBotRole.Arn
      DataPrivacy:
        ChildDirected: false
      IdleSessionTTLInSeconds: 300
      BotLocales:
        - LocaleId: en_US
          NluConfidenceThreshold: 0.40
          VoiceSettings:
            VoiceId: Joanna
          Intents:
            - Name: FallbackIntent
              ParentIntentSignature: AMAZON.FallbackIntent
              InitialResponseSetting:
                InitialResponse:
                  MessageGroupsList:
                    - Message:
                        PlainTextMessage:
                          Value: "I'm sorry, I didn't understand that. Could you please repeat it?"
                NextStep:
                  DialogAction:
                    Type: EndConversation
                    SuppressNextMessage: true

Outputs:
  OpenSearchDomainEndpoint:
    Value: !GetAtt OpenSearchDomain.DomainEndpoint
    Export:
      Name: !Sub ${AWS::StackName}-OpenSearchEndpoint
  BedrockKnowledgeBaseId:
    Value: !Ref BedrockKnowledgeBase
    Export:
      Name: !Sub ${AWS::StackName}-BedrockKnowledgeBaseId
  LexBotId:
    Value: !Ref GenAIBot
    Export:
      Name: !Sub ${AWS::StackName}-LexBotId
