AWSTemplateFormatVersion: '2010-09-09'
Description: 'GenAI Bot - AI Services Stack (OpenSearch, Lex)'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, prod]
    Description: Environment name
  ProjectId:
    Type: String
    Description: Project ID
  PortfolioId:
    Type: String
    Description: Portfolio ID
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of Subnet IDs

Resources:
  # OpenSearch Domain
  OpenSearchDomain:
    Type: AWS::OpenSearchService::Domain
    Properties:
      DomainName: !Sub chatbot-${ProjectId}-${PortfolioId}-${Environment}-os
      VPCOptions:
        SubnetIds: 
          - !Select [0, !Ref SubnetIds]
        SecurityGroupIds:
          - !Ref OpenSearchSecurityGroup
      EngineVersion: 'OpenSearch_2.11'
      ClusterConfig:
        InstanceType: 't3.small.search'
        InstanceCount: 1
        DedicatedMasterEnabled: false
        ZoneAwarenessEnabled: false
      EBSOptions:
        EBSEnabled: true
        VolumeSize: 10
        VolumeType: gp3
      EncryptionAtRestOptions:
        Enabled: true
      NodeToNodeEncryptionOptions:
        Enabled: true
      DomainEndpointOptions:
        EnforceHTTPS: true
        TLSSecurityPolicy: Policy-Min-TLS-1-2-2019-07
      AccessPolicies:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'es:*'
            Resource: !Sub 'arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/chatbot-${ProjectId}-${PortfolioId}-${Environment}-os/*'

  # Lex Bot Role
  LexBotRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lex.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LexRuntimePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - polly:SynthesizeSpeech
                Resource: '*'

  OpenSearchSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for OpenSearch
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0


  # Lex Bot (Basic Placeholder)
  GenAIBot:
    Type: AWS::Lex::Bot
    Properties:
      Name: !Sub GenAIBot_${Environment}
      RoleArn: !GetAtt LexBotRole.Arn
      DataPrivacy:
        ChildDirected: false
      IdleSessionTTLInSeconds: 300
      BotLocales:
        - LocaleId: en_US
          NluConfidenceThreshold: 0.40
          VoiceSettings:
            VoiceId: Joanna
          Intents:
            - Name: FallbackIntent
              ParentIntentSignature: AMAZON.FallbackIntent
              InitialResponseSetting:
                InitialResponse:
                  MessageGroupsList:
                    - Message:
                        PlainTextMessage:
                          Value: "I'm sorry, I didn't understand that. Could you please repeat it?"
                NextStep:
                  DialogAction:
                    Type: EndConversation
                    SuppressNextMessage: true

  # Bedrock Knowledge Base Implementation
  # -------------------------------------
  
  BedrockExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: bedrock.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: BedrockKBPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: bedrock:InvokeModel
                Resource: !Sub 'arn:aws:bedrock:${AWS::Region}::foundation-model/amazon.titan-embed-text-v2:0'
              - Effect: Allow
                Action: aoss:APIAccessAll
                Resource: !Sub 'arn:aws:aoss:${AWS::Region}:${AWS::AccountId}:collection/*'
              - Effect: Allow
                Action: 
                  - s3:ListBucket
                  - s3:GetObject
                Resource: 
                  - !Sub 'arn:aws:s3:::${ProjectId}-${PortfolioId}-chatbot-${Environment}-kb-${AWS::AccountId}'
                  - !Sub 'arn:aws:s3:::${ProjectId}-${PortfolioId}-chatbot-${Environment}-kb-${AWS::AccountId}/*'

  BedrockKBCollection:
    Type: AWS::OpenSearchServerless::Collection
    Properties:
      Name: !Sub 'kb-${ProjectId}-${PortfolioId}-${Environment}'
      Type: VECTORSEARCH
      Description: Collection for Bedrock Knowledge Base
    DependsOn: BedrockKBEncryptionPolicy

  BedrockKBEncryptionPolicy:
    Type: AWS::OpenSearchServerless::SecurityPolicy
    Properties:
      Name: !Sub 'kb-enc-${ProjectId}-${PortfolioId}-${Environment}'
      Type: encryption
      Policy: !Sub >-
        {
          "Rules": [
            {
              "ResourceType": "collection",
              "Resource": ["collection/kb-${ProjectId}-${PortfolioId}-${Environment}"]
            }
          ],
          "AWSOwnedKey": true
        }

  BedrockKBNetworkPolicy:
    Type: AWS::OpenSearchServerless::SecurityPolicy
    Properties:
      Name: !Sub 'kb-net-${ProjectId}-${PortfolioId}-${Environment}'
      Type: network
      Policy: !Sub >-
        [
          {
            "Description": "Public access for KB collection",
            "Rules": [
              {
                "ResourceType": "collection",
                "Resource": ["collection/kb-${ProjectId}-${PortfolioId}-${Environment}"]
              },
              {
                "ResourceType": "dashboard",
                "Resource": ["collection/kb-${ProjectId}-${PortfolioId}-${Environment}"]
              }
            ],
            "AllowFromPublic": true
          }
        ]

  BedrockKBAccessPolicy:
    Type: AWS::OpenSearchServerless::AccessPolicy
    Properties:
      Name: !Sub 'kb-acc-${ProjectId}-${PortfolioId}-${Environment}'
      Type: data
      Policy: !Sub >-
        [
          {
            "Rules": [
              {
                "ResourceType": "collection",
                "Resource": ["collection/kb-${ProjectId}-${PortfolioId}-${Environment}"],
                "Permission": [
                  "aoss:CreateCollectionItems",
                  "aoss:DeleteCollectionItems",
                  "aoss:UpdateCollectionItems",
                  "aoss:DescribeCollectionItems"
                ]
              },
              {
                "ResourceType": "index",
                "Resource": ["index/kb-${ProjectId}-${PortfolioId}-${Environment}/*"],
                "Permission": [
                  "aoss:CreateIndex",
                  "aoss:DeleteIndex",
                  "aoss:UpdateIndex",
                  "aoss:DescribeIndex",
                  "aoss:ReadDocument",
                  "aoss:WriteDocument"
                ]
              }
            ],
            "Principal": [
              "${BedrockExecutionRole.Arn}",
              "arn:aws:iam::${AWS::AccountId}:role/Admin",
              "arn:aws:iam::${AWS::AccountId}:root",
              "arn:aws:iam::${AWS::AccountId}:user/sourav"
            ]
          }
        ]

#   BedrockKnowledgeBase:
#     Type: AWS::Bedrock::KnowledgeBase
#     Properties:
#       Name: !Sub 'knowledge-base-${ProjectId}-${PortfolioId}-${Environment}'
#       RoleArn: !GetAtt BedrockExecutionRole.Arn
#       KnowledgeBaseConfiguration:
#         Type: VECTOR
#         VectorKnowledgeBaseConfiguration:
#           EmbeddingModelArn: !Sub 'arn:aws:bedrock:${AWS::Region}::foundation-model/amazon.titan-embed-text-v2:0'
#       StorageConfiguration:
#         Type: OPENSEARCH_SERVERLESS
#         OpensearchServerlessConfiguration:
#           CollectionArn: !GetAtt BedrockKBCollection.Arn
#           VectorIndexName: 'bedrock-knowledge-base-default-index'
#           FieldMapping:
#             VectorField: 'bedrock-knowledge-base-default-vector'
#             TextField: 'AMAZON_BEDROCK_TEXT'
#             MetadataField: 'AMAZON_BEDROCK_METADATA'
#     DependsOn: BedrockKBAccessPolicy

#   BedrockDataSource:
#     Type: AWS::Bedrock::DataSource
#     Properties:
#       KnowledgeBaseId: !Ref BedrockKnowledgeBase
#       Name: !Sub 'datasource-${ProjectId}-${PortfolioId}-${Environment}'
#       DataSourceConfiguration:
#         Type: S3
#         S3Configuration:
#           BucketArn: !Sub 'arn:aws:s3:::${ProjectId}-${PortfolioId}-chatbot-${Environment}-kb-${AWS::AccountId}'

# ERROR
### The following resource(s) failed to create: [BedrockKnowledgeBase].
##Resource handler returned message: "The specified embedding model arn:aws:bedrock:us-east-1::foundation-model/amazon.titan-embed-image-v1 is not supported. (Service: BedrockAgent, Status Code: 400, Request ID: 729fb5a8-b5b4-4fc1-8aa2-bfb766a541b4) (SDK Attempt Count: 1)" (RequestToken: a9554721-7d41-4b37-0bbb-8755e2a0c72e, HandlerErrorCode: InvalidRequest)


Outputs:
  OpenSearchDomainEndpoint:
    Value: !GetAtt OpenSearchDomain.DomainEndpoint
    Export:
      Name: !Sub ${AWS::StackName}-OpenSearchEndpoint
  # LexBotId:
  #   Value: !Ref GenAIBot
  #   Export:
  #     Name: !Sub ${AWS::StackName}-LexBotId
