AWSTemplateFormatVersion: '2010-09-09'
Description: 'GenAI Bot - Database Stack (DynamoDB)'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, prod]
    Description: Environment name
  ProjectId:
    Type: String
    Description: Project ID
  PortfolioId:
    Type: String
    Description: Portfolio ID

Resources:
  ConfigTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${ProjectId}-${PortfolioId}-Chatbot-${Environment}-Config
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: configKey
          AttributeType: S
      KeySchema:
        - AttributeName: configKey
          KeyType: HASH

  ChatHistoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${ProjectId}-${PortfolioId}-Chatbot-${Environment}-History
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE

Outputs:
  ConfigTableName:
    Value: !Ref ConfigTable
    Export:
      Name: !Sub ${AWS::StackName}-ConfigTableName
  ChatHistoryTableName:
    Value: !Ref ChatHistoryTable
    Export:
      Name: !Sub ${AWS::StackName}-ChatHistoryTableName
