AWSTemplateFormatVersion: '2010-09-09'
Description: 'Document Pipeline - Messaging Stack (SNS)'

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Environment name
  ProjectId:
    Type: String
    Description: Project ID
  PortfolioId:
    Type: String
    Description: Portfolio ID
  StackName:
    Type: String
    Description: Name of the stack
  KmsKeyArn:
    Type: String
    Description: ARN of KMS Key for encryption

Resources:
  TextractJobCompleteTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${ProjectId}-${PortfolioId}-${StackName}-${Environment}-textract-complete
      KmsMasterKeyId: !Ref KmsKeyArn

  # --------------------------------------------------------------------------
  # SQS Queues for Input Buffering
  # --------------------------------------------------------------------------
  DocumentUploadDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${ProjectId}-${PortfolioId}-${StackName}-${Environment}-doc-upload-dlq
      MessageRetentionPeriod: 1209600 # 14 days
      KmsMasterKeyId: !Ref KmsKeyArn

  DocumentUploadQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${ProjectId}-${PortfolioId}-${StackName}-${Environment}-doc-upload-queue
      MessageRetentionPeriod: 345600 # 4 days
      VisibilityTimeout: 300 # Should be >= Lambda timeout
      KmsMasterKeyId: !Ref KmsKeyArn
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DocumentUploadDLQ.Arn
        maxReceiveCount: 3

  # Allow EventBridge to send messages to the Queue
  DocumentUploadQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref DocumentUploadQueue
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt DocumentUploadQueue.Arn
            Condition:
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt DocumentUploadQueue.Arn

  # --------------------------------------------------------------------------
  # SQS Queues for Textract Completion (New)
  # --------------------------------------------------------------------------
  TextractCompleteDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${ProjectId}-${PortfolioId}-${StackName}-${Environment}-textract-complete-dlq
      MessageRetentionPeriod: 1209600 # 14 days
      KmsMasterKeyId: !Ref KmsKeyArn

  TextractCompleteQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${ProjectId}-${PortfolioId}-${StackName}-${Environment}-textract-complete-queue
      MessageRetentionPeriod: 345600 # 4 days
      VisibilityTimeout: 300
      KmsMasterKeyId: !Ref KmsKeyArn
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt TextractCompleteDLQ.Arn
        maxReceiveCount: 3

  TextractCompleteQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref TextractCompleteQueue
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt TextractCompleteQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref TextractJobCompleteTopic

  TextractCompleteSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref TextractJobCompleteTopic
      Endpoint: !GetAtt TextractCompleteQueue.Arn
      Protocol: sqs

Outputs:
  TextractJobCompleteTopicArn:
    Value: !Ref TextractJobCompleteTopic
    Export:
      Name: !Sub ${StackName}-TextractJobCompleteTopicArn
  DocumentUploadQueueArn:
    Value: !GetAtt DocumentUploadQueue.Arn
    Export:
      Name: !Sub ${StackName}-DocumentUploadQueueArn
  DocumentUploadQueueUrl:
    Value: !Ref DocumentUploadQueue
    Export:
      Name: !Sub ${StackName}-DocumentUploadQueueUrl
  TextractCompleteQueueArn:
    Value: !GetAtt TextractCompleteQueue.Arn
    Export:
      Name: !Sub ${StackName}-TextractCompleteQueueArn
