AWSTemplateFormatVersion: '2010-09-09'
Description: 'GenAI Bot - Root Stack (Phase 1: Core)'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, prod]
    Description: Environment name
  S3TemplateBucket:
    Type: String
    Description: S3 Bucket where nested templates are stored
  ProjectId:
    Type: String
    Default: '034'
    Description: Project ID
  PortfolioId:
    Type: String
    Default: '0020'
    Description: Portfolio ID
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID for deployment
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of Subnet IDs for deployment

Resources:
  AuthStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${S3TemplateBucket}/genai-bot-copy/auth.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectId: !Ref ProjectId
        PortfolioId: !Ref PortfolioId

  DatabaseStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${S3TemplateBucket}/genai-bot-copy/database.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectId: !Ref ProjectId
        PortfolioId: !Ref PortfolioId

  StorageS3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${S3TemplateBucket}/genai-bot-copy/storage-s3.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectId: !Ref ProjectId
        PortfolioId: !Ref PortfolioId

  AIServicesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${S3TemplateBucket}/genai-bot-copy/ai-services.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectId: !Ref ProjectId
        PortfolioId: !Ref PortfolioId
        VpcId: !Ref VpcId
        SubnetIds: !Join [",", !Ref SubnetIds]

  ComputeStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: [DatabaseStack, AIServicesStack]
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${S3TemplateBucket}/genai-bot-copy/compute.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectId: !Ref ProjectId
        PortfolioId: !Ref PortfolioId
        VpcId: !Ref VpcId
        SubnetIds: !Join [",", !Ref SubnetIds]
        ConfigTableName: !GetAtt DatabaseStack.Outputs.ConfigTableName
        ChatHistoryTableName: !GetAtt DatabaseStack.Outputs.ChatHistoryTableName
        OpenSearchEndpoint: !GetAtt AIServicesStack.Outputs.OpenSearchDomainEndpoint

  ApiStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: [ComputeStack, AuthStack]
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${S3TemplateBucket}/genai-bot-copy/api.yaml
      Parameters:
        Environment: !Ref Environment
        ProjectId: !Ref ProjectId
        PortfolioId: !Ref PortfolioId
        ContentDesignerFunctionArn: !GetAtt ComputeStack.Outputs.ContentDesignerFunctionArn
        BotFulfillmentFunctionArn: !GetAtt ComputeStack.Outputs.BotFulfillmentFunctionArn
        UserPoolArn: !GetAtt AuthStack.Outputs.UserPoolArn

Outputs:
  ApiEndpoint:
    Value: !GetAtt ApiStack.Outputs.ApiEndpoint
  CognitoUserPoolId:
    Value: !GetAtt AuthStack.Outputs.UserPoolId
