AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for PDF ingestion, Textract processing, and Salesforce integration.

Globals:
  Function:
    Timeout: 60
    MemorySize: 256
    Runtime: python3.12

Resources:

  ## Lambda #1 (Triggered by EventBridge Rule #1)
  EventBridgeLambdaOne:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/lambda_one/
      Handler: app.lambda_handler
      Description: "Lambda triggered by EventBridge Rule #1"
      Events:
        ScheduleOne:
          Type: Schedule
          Properties:
            # Example: Run every day at 1 AM UTC
            Schedule: cron(0 1 * * ? *)

  ## Lambda #2 (Triggered by EventBridge Rule #2)
  EventBridgeLambdaTwo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/lambda_two/
      Handler: app.lambda_handler
      Description: "Lambda triggered by EventBridge Rule #2"
      Events:
        ScheduleTwo:
          Type: Schedule
          Properties:
            # Example: Run every day at 2 AM UTC
            Schedule: cron(0 2 * * ? *)
