AWSTemplateFormatVersion: "2010-09-09"
Description: Parent stack for GenAI Chat Bot using Nested Stacks

Parameters:
  ProjectName:
    Type: String
    Default: genai-chat-bot
  # VPC Parameters
  VPCCidr:
    Type: String
    Default: 10.0.0.0/16
  PublicSubnet1Cidr:
    Type: String
    Default: 10.0.1.0/24
  PublicSubnet2Cidr:
    Type: String
    Default: 10.0.2.0/24
  PrivateSubnet1Cidr:
    Type: String
    Default: 10.0.3.0/24
  PrivateSubnet2Cidr:
    Type: String
    Default: 10.0.4.0/24

  LambdaFunctionName:
    Type: String
    Default: api-lambda
  LambdaRuntime:
    Type: String
    Default: python3.11
  ApiName:
    Type: String
    Default: chat-api
  ApiStageName:
    Type: String
    Default: dev
  AuditBucketName:
    Type: String
    Default: audit-logs-bucket
  LexBotName:
    Type: String
    Default: GenAIChatBot

Resources:
  NetworkingStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: networking.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        VPCCidr: !Ref VPCCidr
        PublicSubnet1Cidr: !Ref PublicSubnet1Cidr
        PublicSubnet2Cidr: !Ref PublicSubnet2Cidr
        PrivateSubnet1Cidr: !Ref PrivateSubnet1Cidr
        PrivateSubnet2Cidr: !Ref PrivateSubnet2Cidr

  # S3Stack:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: s3.yml
  #     Parameters:
  #       AuditBucketName: !Ref AuditBucketName

  # IAMStack:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: iam.yml
  #     Parameters:
  #       ProjectName: !Ref ProjectName
  #       AuditBucketArn: !GetAtt S3Stack.Outputs.AuditBucketArn

  # LambdaStack:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: lambda.yml
  #     Parameters:
  #       LambdaFunctionName: !Ref LambdaFunctionName
  #       LambdaRuntime: !Ref LambdaRuntime
  #       LambdaRoleArn: !GetAtt IAMStack.Outputs.LambdaRoleArn
  #       AuditBucketName: !GetAtt S3Stack.Outputs.AuditBucketName
  #       VPCId: !GetAtt NetworkingStack.Outputs.VPCId
  #       SubnetIds: !GetAtt NetworkingStack.Outputs.PrivateSubnetIds
  #       SecurityGroupId: !GetAtt NetworkingStack.Outputs.LambdaSecurityGroupId

  # ApiGatewayStack:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: apigateway.yml
  #     Parameters:
  #       ApiName: !Ref ApiName
  #       ApiStageName: !Ref ApiStageName
  #       LambdaFunctionArn: !GetAtt LambdaStack.Outputs.LambdaFunctionArn

  # LexBotStack:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: lexbot.yml
  #     Parameters:
  #       LexBotName: !Ref LexBotName
  #       LambdaFunctionArn: !GetAtt LambdaStack.Outputs.LambdaFunctionArn

Outputs:
  VPCId:
    Value: !GetAtt NetworkingStack.Outputs.VPCId
  PrivateSubnetIds:
    Value: !GetAtt NetworkingStack.Outputs.PrivateSubnetIds
  # LambdaSecurityGroupId:
  #   Value: !GetAtt NetworkingStack.Outputs.LambdaSecurityGroupId
  # ApiInvokeURL:
  #   Value: !GetAtt ApiGatewayStack.Outputs.ApiInvokeURL
  # LambdaFunctionArn:
  #   Value: !GetAtt LambdaStack.Outputs.LambdaFunctionArn
  # LambdaRoleArn:
  #   Value: !GetAtt IAMStack.Outputs.LambdaRoleArn
  # AuditBucketArn:
  #   Value: !GetAtt S3Stack.Outputs.AuditBucketArn
  # LexBotId:
  #   Value: !GetAtt LexBotStack.Outputs.LexBotId
