name: Deploy CloudFormation

on:
  push:
    branches:
      - "test-branch1"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Set up Python (needed for SAM CLI)
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - name: Build SAM App
        run: sam build

      - name: Deploy SAM App
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name genai-chat-bot --capabilities CAPABILITY_IAM
