name: Deploy CloudFormation

on:
  push:
    branches:
      - "test-branch"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - name: Upload CFT to S3
        run: |
          aws s3 cp ./cft s3://henry-sourav-workspace/ --recursive

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file bot.yaml \
            --stack-name genai-chat-bot \
            --capabilities CAPABILITY_NAMED_IAM \
            --s3-bucket henry-sourav-workspace

      # - name: Show Stack Outputs
      #   run: |
      #     aws cloudformation describe-stacks \
      #       --stack-name MyStack \
      #       --query "Stacks[0].Outputs"
